"""update

Revision ID: 186c057205f9
Revises: a4144eb72ff5
Create Date: 2023-03-08 01:24:55.524104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '186c057205f9'
down_revision = 'a4144eb72ff5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
