"""update

Revision ID: 3f8b724d7ee0
Revises: 186c057205f9
Create Date: 2023-03-08 01:25:43.304230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f8b724d7ee0'
down_revision = '186c057205f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
