"""Added Model

Revision ID: 4d2b14faa4d2
Revises: d2c7ab3fa531
Create Date: 2023-03-06 23:39:21.998634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d2b14faa4d2'
down_revision = 'd2c7ab3fa531'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owners', 'hourly_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owners', sa.Column('hourly_rate', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
