"""class

Revision ID: 6584ff5d7c88
Revises: 7688a192cb16
Create Date: 2023-03-07 00:05:48.614240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6584ff5d7c88'
down_revision = '7688a192cb16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
