"""update

Revision ID: c38d7b79b771
Revises: 3f8b724d7ee0
Create Date: 2023-03-08 01:51:15.595574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c38d7b79b771'
down_revision = '3f8b724d7ee0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
